apiVersion: v1
entries:
  jenkins-operator:
  - apiVersion: v1
    appVersion: 0.3.3
    created: 2020-01-30T23:16:18.475679338+01:00
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: d7e50755cd35ab9b99c755ea56e5f5bcd53e1d7c70b32c146ed05de80aa05115
    icon: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/assets/jenkins-operator-icon.png
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v1
    appVersion: 0.3.2
    created: 2020-01-30T23:16:18.477081893+01:00
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: a64b28ee639a2c2af662f66437db497dcdd36742c50aa664cfd6d023f8e6d4bd
    icon: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/assets/jenkins-operator-icon.png
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: 0.3.1
    created: 2020-01-30T23:16:18.476816221+01:00
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: e6914be2c96a7ae8c7794e0d356b073394d1ee99465c7a26aeb77a22a5b4b22d
    icon: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/assets/jenkins-operator-icon.png
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v1
    appVersion: 0.3.0
    created: 2020-01-30T23:16:18.476593707+01:00
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: 82d3748cce50ebc9fdcebba419c11dac0557e5ba2441b8deb5da49aa879b692a
    icon: https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/assets/jenkins-operator-icon.png
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v1
    appVersion: 0.2.2
    created: 2020-01-30T23:16:18.476369312+01:00
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: 2b2e4d9399fdf49e6ed33753fd69619068da16b1ffbae6f27bce89cbf83e8174
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    appVersion: 0.2.2
    created: 2020-01-30T23:16:18.476133977+01:00
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: 16229e795a171427cd019fd623569aab1672618d7bc1d6b2c9fd627310fa00ef
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.2.tgz
    version: 0.0.2
  - apiVersion: v1
    appVersion: 0.2.0
    created: 2020-01-30T23:16:18.475906896+01:00
    description: Kubernetes native operator which fully manages Jenkins on Kubernetes
    digest: d5828cba35e435fc6526d235ec98b3ffdb8d6ed20b82c953a81a5c1f660d1fb3
    name: jenkins-operator
    urls:
    - https://raw.githubusercontent.com/jenkinsci/kubernetes-operator/master/chart/jenkins-operator/jenkins-operator-0.0.1.tgz
    version: 0.0.1
generated: 2020-01-30T23:16:18.475005183+01:00
