{{ if eq (include "jenkins-operator.watchAllNamespaces" .) "true" }}
{{- /*
# Special case where WATCH_NAMESPACE is set to an empty string, which makes the
# operator watch all namespaces (see jenkins-operator.watchAllNamespaces). In this
# case we need to create clusterrole and clusterrolebinding instead of role and
# rolebinding
*/ -}}
  {{- template "jenkins-operator.role" "" }}
{{ else }}
  {{- template "jenkins-operator.role" .Release.Namespace }}
  {{- if ne .Release.Namespace .Values.jenkins.namespace -}}
    {{- template "jenkins-operator.role" .Values.jenkins.namespace }}
  {{- end }}
{{ end }}