version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      golang:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/website"
    schedule:
      interval: "daily"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions:
        patterns:
          - "*"
