# Configuration for probot-stale - https://github.com/probot/stale

# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30

# Number of days of inactivity before a stale Issue or Pull Request is closed.
# Set to false to disable. If disabled, issues still need to be closed manually, but will remain marked as stale.
daysUntilClose: 30

# Issues with these labels will never be considered stale
exemptLabels:
  - frozen

# Set to true to ignore issues in a milestone (defaults to false)
exemptMilestones: true

# Label to use when marking an issue as stale
staleLabel: stale

issues:
  # Comment to post when marking an issue as stale. Set to `false` to disable
  markComment: >
    This issue has been automatically marked as stale because it has not had recent activity.
    It will be closed if no further activity occurs.
    If this issue is still affecting you, just comment with any updates and we'll keep it open.
    Thank you for your contributions.

  # Comment to post when closing a stale issue. Set to `false` to disable
  closeComment: >
    Closing this issue after a prolonged period of inactivity.
    If this issue is still present in the latest release, please create a new issue with up-to-date information. Thank you!

pulls:
  # Comment to post when marking a pull request as stale.
  markComment: >
    This pull request has been automatically marked as stale because it has not had recent activity.
    It will be closed if no further activity occurs.
    If this pull request is still relevant, just comment with any updates and we'll keep it open.
    Thank you for your contributions.

  # Comment to post when closing a stale pull request. Set to `false` to disable
  closeComment: >
    Closing this pull request after a prolonged period of inactivity.
    If this issue is still present in the latest release, please ask for this pull request to be reopened. Thank you!

# Limit the number of actions per hour, from 1-30. Default is 30
limitPerRun: 30
