version: "2"
run:
  allow-parallel-runners: true
output:
  sort-order:
    - file
    - severity
    - linter
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
        path: internal/*
      - linters:
          - dupl
        path: (.+)_test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
