run:
  deadline: 5m
  allow-parallel-runners: true
  skip-files:
    - api/v1alpha2/zz_generated.deepcopy.go
issues:
  exclude-use-default: false
  exclude-rules:
    - path: "internal/*"
      linters:
        - dupl
    - path: (.+)_test.go
      linters:
        - dupl
linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - exportloopref
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    # - prealloc
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
output:
  sort-results: true
  sort-order:
    - file
    - severity
    - linter
