repos:
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.51.2
    hooks:
      - id: golangci-lint
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: detect-private-key
      - id: check-yaml
      - id: trailing-whitespace
      - id: end-of-file-fixer
