apiVersion: jenkins.io/v1alpha2
kind: JenkinsImage
metadata:
  name: simple-jenkinsimage
spec:
  image:
    name: jenkins/jenkins
    tag: 2.277.4-lts-alpine
  plugins:
  - name: kubernetes
    version: "1.29.4"
  - name: workflow-job
    version: "2.40"
  - name: workflow-aggregator
    version: "2.6"
  - name: git
    version: "4.6.0"
  - name: job-dsl
    version: "1.77"
  - name: configuration-as-code
    version: "1.51"
  - name: kubernetes-credentials-provider
    version: "0.18-1"

