apiVersion: jenkins.io/v1alpha2
kind: JenkinsImage
metadata:
  name: simple-jenkinsimage
spec:
  image:
    name: jenkins/jenkins
    tag: 2.263.1-lts-alpine
  plugins:
  - name: kubernetes
    version: "1.28.6"
  - name: workflow-job
    version: "2.40"
  - name: workflow-aggregator
    version: "2.6"
  - name: git
    version: "4.5.0"
  - name: job-dsl
    version: "1.77"
  - name: configuration-as-code
    version: "1.46"
  - name: kubernetes-credentials-provider
    version: "0.15"

