apiVersion: v1
kind: Service
metadata:
# need to specify a relevant internal load balancer annotation to get an internal loadbalancer provisioned.
  name: jenkins-deployment
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: jenkins-app
  sessionAffinity: None
#  type: NodePort   #use this for minikube testing and do minikube service to simulate load balancing
  type: LoadBalancer
  sessionAffinity: ClientIP