name: "Stale issue automation"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@5bef64f19d7facfb25b37b414482c7164d639639 # v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 200
          days-before-issue-stale: 60
          days-before-issue-close: 10
          exempt-pr-labels: "not-stale"
          exempt-issue-labels: "not-stale"
