name: codespell
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
jobs:
  codespell:
    name: codespell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          ignore_words_list: aks,ags,startin
          skip: "*.js,package-lock.json,*.lock,*/Font-Awesome/*,*.toml,*.svg,*assets/vendor/bootstrap*,cert-manager.crds.yaml"
