name: Run Helm e2e tests
on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - 'assets/**'
      - 'backup/**'
      - '*.md'
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
    paths-ignore:
      - 'docs/**'
      - 'website/**'
      - 'assets/**'
      - 'backup/**'
      - '*.md'

jobs:
  create-tests-list:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v4
    - id: matrix
      run: |
        script=$(./test/make_matrix_ginkgo.sh helm)
        echo "matrix=${script}" >> $GITHUB_OUTPUT

  run-helm-tests:
    runs-on: ubuntu-latest
    needs: [create-tests-list]
    if: github.event.pull_request.draft == false
    name: Run automated helm tests
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.create-tests-list.outputs.matrix) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up env vars
        run: |
          echo "GO111MODULE=on" >> $GITHUB_ENV
          echo "GO_VERSION=v$(sed -n 's/GO_VERSION=//p' config.base.env | tr -d '\n' | tr -d '"')" >> $GITHUB_ENV
          echo "HELM_VERSION=v$(sed -n 's/HELM_VERSION=//p' config.base.env | tr -d '\n' | tr -d '"')" >> $GITHUB_ENV
          echo "KIND_CLUSTER_NAME=$(sed -n 's/KIND_CLUSTER_NAME=//p' config.base.env | tr -d '\n' | tr -d '"')" >> $GITHUB_ENV
          echo "GOPATH=/home/runner/go" >> $GITHUB_ENV

      - name: Prepare go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Ensure Golang runtime dependencies
        run: make go-dependencies

      - name: Verify code formatting
        run: make verify

      - name: Kind setup
        uses: helm/kind-action@v1.9.0
        with:
          cluster_name: ${{env.KIND_CLUSTER_NAME}}
          config: kind-cluster.yaml

      - name: Prepare environment for e2e
        run: |
          sudo apt-get update
          sudo apt-get install socat
          sudo mkdir -p $HOME/.kube
          sudo chown -R $USER $HOME/.kube

      - name: Jenkins Operator - Helm Chart tests
        env:
          TNAME: ${{ matrix.test }}
          TFILE: ${{ matrix.test }}
          TLINE: ${{ matrix.test }}
        run: |
          git reset --hard
          make helm-lint
          echo "Running test: ${TNAME} from file: ${TFILE} line: ${TLINE}"
          make helm-e2e E2E_TEST_ARGS='-ginkgo.v -ginkgo.focus="${TNAME}"'
