name: CI Lint
on:
  push:
    branches:
      - master
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
jobs:
  codespell:
    name: Codespell
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Codespell
      uses: codespell-project/actions-codespell@v2
      with:
        check_filenames: true
        ignore_words_list: aks,ags,startin
        skip: "*.js,package-lock.json,*.lock,*/Font-Awesome/*,*.toml,*.svg,*assets/vendor/bootstrap*,cert-manager.crds.yaml"
  pre-commit:
    name: PreCommit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5.0.0
    - uses: DeterminateSystems/nix-installer-action@v10
      with:
        diagnostic-endpoint: ""
    - uses: DeterminateSystems/magic-nix-cache-action@v4
      with:
        diagnostic-endpoint: ""
    - name: Checkout
      uses: actions/checkout@v4
    - id: files
      uses: tj-actions/changed-files@v43
    - name: nix checks
      run: nix flake check
    - name: nix pre-commit
      run: nix develop . --command pre-commit run --files ${{ steps.files.outputs.all_changed_files }} --show-diff-on-failure
